# x=1
# y=2
# x=[4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295]
# y=[4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295]
x=[0, 0, 0, 0, 1, 0, 0, 0]
y=[9, 9, 2, 0, 0, 0, 0, 0]
return=""